### ISSUE TITLE
Error: undeclared identifier: 'none'

### ISSUE THREAD

**Issue by delemercier** [soasme/nim-schedules#1]
Hello,

This library seems great, but I can't even execute the README example.

Env: nim 1.2.0

I created a main.nim file with the code in Usage (README) and executed:
nim c --threads:on main.nim

I get this error:
C:\nim\main.nim(3, 1) template/generic instantiation of `schedules` from here
C:\user\path\.nimble\pkgs\schedules-0.1.0\schedules.nim(252, 32) Error: undeclared identifier: 'none'

Bye

**Comment by skellock** [comment]
Add `import options` into your `main.nim`.

When you use macros like `schedules` does, you can run into scoping situations where dependencies (ie. `options`) of the module you're importing (`schedules.nim`) doesn't carry everything needed into the destination module (your `main.nim`).

This is by (Nim's) design. 

I've seen libraries deal with two ways:

1. Tell people to do it themselves `import options`
2. Or do it for them `export options` (from within `schedules.nim`).

This is how I understand it.

However, I am not a smart man.

**Comment by SolitudeSF** [comment]
no, its a bug in `schedules`. it should use `bindSym` to construct calls.
